[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "MAOS"
version = "0.0.1"
description = "Multi-Agent Operating System"
license = "MIT"
authors = ["Everett Kleven <ekleven@vangelis.tech>"]
homepage = "https://github.com/vangelistechnologies/persist"
documentation = "https://www.vangelis.tech"
readme = "README.md"
repository = "https://github.com/kyegomez/swarms"
keywords = [
    "artificial intelligence",
    "machine learning",
    "deep learning",
    "prompt engineering",
    "agents",
    "Agents",
    "llms",
    "LLMs",
    "Large Language Models",
    "Generative AI",
    "GenAI",
    "RAG",
    "Retrieval Augmented Generation",
    "Chunking",
    "Embeddings",
    "Segmentation",
    "transformers",
    "Enterprise-Grade Agents",
    "Production-Grade Agents",
    "Multi-Grade-Agents",
    "Swarms",
    "Transformers",
    "mixture of experts",
    "MoE",
    "Multi-Agent Operating System",
    "MAOS",
    ""

    "Prompt Engineering",
    "Agents",
    "Generative Agents",
    "Generative AI",
    "Agent Marketplace",
    "Agent Store",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
]


[tool.poetry.dependencies]
python = ">=3.10,<4.0"
python-dotenv = "*"
fastapi = ">=0.112.1"
pydantic = "2.8.2"
getdaft = "^0.2.33"
ray = "^2.34.0"
asyncio = ">=3.4.3,<4.0"

transformers = ">= 4.39.0, <5.0.0"
torch = ">=2.1.1,<3.0"

pypdf = "4.3.1"
ratelimit = "2.2.1"
tenacity = "8.5.0"
faiss-gpu-raft = "1.8.0"

PyYAML = "*"
docstring_parser = "0.16"

openai = ">=1.30.1,<2.0"
tiktoken = "*"
networkx = "*"


# [tool.poetry.scripts]
# swarms = "swarms.cli:main"

[tool.poetry.group.lint.dependencies]
black = ">=23.1,<25.0"
ruff = ">=0.5.1,<0.5.8"
types-toml = "^0.10.8.1"
types-pytz = ">=2023.3,<2025.0"
types-chardet = "^5.0.4.6"
mypy-protobuf = "^3.0.0"


[tool.poetry.group.test.dependencies]
pytest = "^8.1.1"
termcolor = "^2.4.0"
pandas = "^2.2.2"
fastapi = "^0.110.1"

[tool.ruff]
line-length = 75

[tool.black]
target-version = ["py38"]
line-length = 75
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | docs
)/
'''
