[tool.black]
line-length = 88
target-version = ["py38"]
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.venv
  | build
  | dist
  | api/config/context/clients/daft\.py
  | api/config/context/clients/lancedb\.py
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
default_section = "THIRDPARTY"
skip_glob = ["api/config/context/clients/daft.py", "api/config/context/clients/lancedb.py"]

[tool.flake8]
max-line-length = 88
extend-ignore = E203, E266, E501, W503, F403, F401
exclude =
    .git,
    __pycache__,
    build,
    dist,
    api/config/context/clients/daft.py,
    api/config/context/clients/lancedb.py

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"