[tool.poetry]
name = "beta"
version = "0.1.0"
description = ""
authors = ["everettVT <everett@vangelis.tech>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
