# settings.dev.yaml

development:
  storage:
    s3:
      region_name: "us-west-2"
      endpoint_url: "https://s3.us-west-2.amazonaws.com"
      access_key_id: "YOUR_SECURE_ACCESS_KEY"
      secret_access_key: "YOUR_SECURE_SECRET_KEY"
      bucket: "dratos-dev"
      folder: "data"
